local E = unpack(ElvUI)
local TUI = E:GetModule('TrenchyUI')

local CATEGORIES_JSON = '{"categories":[{"source":"1","name":"Flask","search":"#flasks phials"},{"source":"2","name":"Utility","search":"#explosives and devices|#other"}],"version":2,"sections":{"1":{"name":"Equipment","color":"D301FF"},"4":{"name":"Consumables","color":"FF2F3D"},"3":{"name":"Housing","color":"00FF33"},"2":{"name":"Crafting","color":"0B99FF"}},"addon":"Baganator","order":["default_auto_recents","----","default_hearthstone","default_questitem","default_keystone","default_key","----","_4","1","default_food","default_potion","2","__end","----","_1","default_auto_equipment_sets","default_weapon","default_armor","default_itemenhancement","__end","----","_2","default_tradegoods","default_recipe","default_reagent","default_profession","default_gem","__end","----","_3","default_housing","__end","----","default_container","default_miscellaneous","default_battlepet","default_toy","default_other","----","default_junk","default_special_empty"],"modifications":[{"showGroupPrefix":true,"source":"1","priority":0,"hideIn":[]},{"showGroupPrefix":true,"source":"default_gem","priority":-1,"hideIn":[]},{"showGroupPrefix":true,"source":"2","priority":0,"hideIn":[]},{"showGroupPrefix":true,"source":"default_armor","priority":-1,"hideIn":[]},{"showGroupPrefix":true,"source":"default_itemenhancement","priority":-1,"hideIn":[]},{"showGroupPrefix":true,"source":"default_consumable","priority":-1,"hideIn":[]},{"showGroupPrefix":true,"source":"default_tradegoods","priority":-1,"hideIn":[]},{"showGroupPrefix":true,"source":"default_housing","priority":-1,"hideIn":[]},{"showGroupPrefix":true,"source":"default_weapon","priority":-1,"hideIn":[]},{"showGroupPrefix":true,"source":"default_auto_equipment_sets","priority":-1,"hideIn":[]},{"showGroupPrefix":true,"source":"default_potion","priority":-1,"hideIn":[]},{"showGroupPrefix":true,"source":"default_food","priority":-1,"hideIn":[]}],"hidden":[]}'

function TUI:ApplyBaganatorProfile()
	if not Baganator or not Baganator.CustomiseDialog or not Baganator.CustomiseDialog.CategoriesImport then return end
	Baganator.CustomiseDialog.CategoriesImport(CATEGORIES_JSON)
end
